package contracts

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// IndexPath is where the generated index lives, relative to the root.
const IndexPath = "api/index.md"

// RenderIndex generates api/index.md from the mirrors under root: one row
// per system with its OpenAPI `info.version`, the pinned commit and the
// endpoint groups of spec 02 §3. The output depends only on the files, so
// CI can regenerate it and fail on any difference.
func RenderIndex(root string) (string, error) {
	mirrors, err := Mirrors(root)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("# National API aggregate\n\n")
	b.WriteString("Generated by `go run ./scripts/contracts index` from the `SOURCE` files\n")
	b.WriteString("and mirrored `openapi.yaml` files under `api/`; do not edit by hand.\n")
	b.WriteString("Each system repository owns its `api/openapi.yaml` (spec `00 §7`); the\n")
	b.WriteString("copies here are read-only mirrors pinned by commit (docs/PLAN.md §3.2).\n")
	b.WriteString("Endpoint groups are the rows of spec `02 §3`; F3411/F3548 rows are\n")
	b.WriteString("standard endpoints defined by uas_standards, not by the national file.\n\n")
	b.WriteString("| System | OpenAPI `info.version` | Pinned commit | Endpoint groups (`02 §3`) |\n")
	b.WriteString("|---|---|---|---|\n")
	pinned := 0
	for _, m := range mirrors {
		if m.Kind != "api" {
			continue
		}
		version, commit := "—", "unpinned (skeleton not published)"
		if m.Source.Pinned() {
			pinned++
			commit = "`" + m.Source.ShortCommit() + "`"
			o, err := ReadOpenAPI(filepath.Join(m.Dir, "openapi.yaml"))
			if err != nil {
				return "", fmt.Errorf("%s: %w", m.System, err)
			}
			version = "`" + o.InfoVersion + "`"
		}
		var groups []string
		for _, g := range GroupsFor(m.System) {
			row := g.Row
			switch {
			case g.Standard:
				row += " (standard)"
			case g.Optional:
				row += " (optional)"
			}
			groups = append(groups, row)
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", m.System, version, commit, strings.Join(groups, "<br>"))
	}
	fmt.Fprintf(&b, "\n%d of %d systems pinned.\n", pinned, len(Systems))
	return b.String(), nil
}

// ReadOpenAPI reads and parses one openapi.yaml.
func ReadOpenAPI(path string) (OpenAPI, error) {
	b, err := os.ReadFile(path) //nolint:gosec // a mirror path under the repository root
	if err != nil {
		return OpenAPI{}, err
	}
	return ParseOpenAPI(b)
}
